/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Cuida API
 * Cuida backend API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  InviteAcceptAcceptOrgInvitation400,
  InviteAcceptAcceptOrgInvitationParams
} from '../cuidaAPI.schemas';

import { customInstance } from '.././custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary AcceptOrgInvitation
 */
export type inviteAcceptAcceptOrgInvitationResponse200 = {
  data: void
  status: 200
}

export type inviteAcceptAcceptOrgInvitationResponse400 = {
  data: InviteAcceptAcceptOrgInvitation400
  status: 400
}

export type inviteAcceptAcceptOrgInvitationResponseSuccess = (inviteAcceptAcceptOrgInvitationResponse200) & {
  headers: Headers;
};
export type inviteAcceptAcceptOrgInvitationResponseError = (inviteAcceptAcceptOrgInvitationResponse400) & {
  headers: Headers;
};

export type inviteAcceptAcceptOrgInvitationResponse = (inviteAcceptAcceptOrgInvitationResponseSuccess | inviteAcceptAcceptOrgInvitationResponseError)

export const getInviteAcceptAcceptOrgInvitationUrl = (params: InviteAcceptAcceptOrgInvitationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/invite/accept?${stringifiedParams}` : `/invite/accept`
}

export const inviteAcceptAcceptOrgInvitation = async (params: InviteAcceptAcceptOrgInvitationParams, options?: RequestInit): Promise<inviteAcceptAcceptOrgInvitationResponse> => {
  
  return customInstance<inviteAcceptAcceptOrgInvitationResponse>(getInviteAcceptAcceptOrgInvitationUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getInviteAcceptAcceptOrgInvitationQueryKey = (params?: InviteAcceptAcceptOrgInvitationParams,) => {
    return [
    `/invite/accept`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getInviteAcceptAcceptOrgInvitationQueryOptions = <TData = Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError = InviteAcceptAcceptOrgInvitation400>(params: InviteAcceptAcceptOrgInvitationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInviteAcceptAcceptOrgInvitationQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>> = ({ signal }) => inviteAcceptAcceptOrgInvitation(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InviteAcceptAcceptOrgInvitationQueryResult = NonNullable<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>>
export type InviteAcceptAcceptOrgInvitationQueryError = InviteAcceptAcceptOrgInvitation400


export function useInviteAcceptAcceptOrgInvitation<TData = Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError = InviteAcceptAcceptOrgInvitation400>(
 params: InviteAcceptAcceptOrgInvitationParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>,
          TError,
          Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInviteAcceptAcceptOrgInvitation<TData = Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError = InviteAcceptAcceptOrgInvitation400>(
 params: InviteAcceptAcceptOrgInvitationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>,
          TError,
          Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInviteAcceptAcceptOrgInvitation<TData = Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError = InviteAcceptAcceptOrgInvitation400>(
 params: InviteAcceptAcceptOrgInvitationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary AcceptOrgInvitation
 */

export function useInviteAcceptAcceptOrgInvitation<TData = Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError = InviteAcceptAcceptOrgInvitation400>(
 params: InviteAcceptAcceptOrgInvitationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInviteAcceptAcceptOrgInvitationQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getInviteAcceptAcceptOrgInvitationSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError = InviteAcceptAcceptOrgInvitation400>(params: InviteAcceptAcceptOrgInvitationParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInviteAcceptAcceptOrgInvitationQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>> = ({ signal }) => inviteAcceptAcceptOrgInvitation(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InviteAcceptAcceptOrgInvitationSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>>
export type InviteAcceptAcceptOrgInvitationSuspenseQueryError = InviteAcceptAcceptOrgInvitation400


export function useInviteAcceptAcceptOrgInvitationSuspense<TData = Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError = InviteAcceptAcceptOrgInvitation400>(
 params: InviteAcceptAcceptOrgInvitationParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInviteAcceptAcceptOrgInvitationSuspense<TData = Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError = InviteAcceptAcceptOrgInvitation400>(
 params: InviteAcceptAcceptOrgInvitationParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInviteAcceptAcceptOrgInvitationSuspense<TData = Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError = InviteAcceptAcceptOrgInvitation400>(
 params: InviteAcceptAcceptOrgInvitationParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary AcceptOrgInvitation
 */

export function useInviteAcceptAcceptOrgInvitationSuspense<TData = Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError = InviteAcceptAcceptOrgInvitation400>(
 params: InviteAcceptAcceptOrgInvitationParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof inviteAcceptAcceptOrgInvitation>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInviteAcceptAcceptOrgInvitationSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




