/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Cuida API
 * Cuida backend API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ActionExecutionResponse,
  ActionGroupType,
  ActionListResponse,
  ActionsActionGroupExecuteAction400,
  ActionsActionGroupListActions400,
  ActionsActionGroupObjectIdExecuteObjectAction400,
  ActionsActionGroupObjectIdListObjectActions400,
  UpdateUserAction
} from '../cuidaAPI.schemas';

import { customInstance } from '.././custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary ListActions
 */
export type actionsActionGroupListActionsResponse200 = {
  data: ActionListResponse
  status: 200
}

export type actionsActionGroupListActionsResponse400 = {
  data: ActionsActionGroupListActions400
  status: 400
}

export type actionsActionGroupListActionsResponseSuccess = (actionsActionGroupListActionsResponse200) & {
  headers: Headers;
};
export type actionsActionGroupListActionsResponseError = (actionsActionGroupListActionsResponse400) & {
  headers: Headers;
};

export type actionsActionGroupListActionsResponse = (actionsActionGroupListActionsResponseSuccess | actionsActionGroupListActionsResponseError)

export const getActionsActionGroupListActionsUrl = (actionGroup: ActionGroupType,) => {


  

  return `/actions/${actionGroup}`
}

export const actionsActionGroupListActions = async (actionGroup: ActionGroupType, options?: RequestInit): Promise<actionsActionGroupListActionsResponse> => {
  
  return customInstance<actionsActionGroupListActionsResponse>(getActionsActionGroupListActionsUrl(actionGroup),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getActionsActionGroupListActionsQueryKey = (actionGroup: ActionGroupType,) => {
    return [
    `/actions/${actionGroup}`
    ] as const;
    }

    
export const getActionsActionGroupListActionsQueryOptions = <TData = Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError = ActionsActionGroupListActions400>(actionGroup: ActionGroupType, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getActionsActionGroupListActionsQueryKey(actionGroup);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof actionsActionGroupListActions>>> = ({ signal }) => actionsActionGroupListActions(actionGroup, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(actionGroup), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ActionsActionGroupListActionsQueryResult = NonNullable<Awaited<ReturnType<typeof actionsActionGroupListActions>>>
export type ActionsActionGroupListActionsQueryError = ActionsActionGroupListActions400


export function useActionsActionGroupListActions<TData = Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError = ActionsActionGroupListActions400>(
 actionGroup: ActionGroupType, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof actionsActionGroupListActions>>,
          TError,
          Awaited<ReturnType<typeof actionsActionGroupListActions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActionsActionGroupListActions<TData = Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError = ActionsActionGroupListActions400>(
 actionGroup: ActionGroupType, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof actionsActionGroupListActions>>,
          TError,
          Awaited<ReturnType<typeof actionsActionGroupListActions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActionsActionGroupListActions<TData = Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError = ActionsActionGroupListActions400>(
 actionGroup: ActionGroupType, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListActions
 */

export function useActionsActionGroupListActions<TData = Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError = ActionsActionGroupListActions400>(
 actionGroup: ActionGroupType, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getActionsActionGroupListActionsQueryOptions(actionGroup,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getActionsActionGroupListActionsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError = ActionsActionGroupListActions400>(actionGroup: ActionGroupType, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getActionsActionGroupListActionsQueryKey(actionGroup);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof actionsActionGroupListActions>>> = ({ signal }) => actionsActionGroupListActions(actionGroup, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ActionsActionGroupListActionsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof actionsActionGroupListActions>>>
export type ActionsActionGroupListActionsSuspenseQueryError = ActionsActionGroupListActions400


export function useActionsActionGroupListActionsSuspense<TData = Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError = ActionsActionGroupListActions400>(
 actionGroup: ActionGroupType, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActionsActionGroupListActionsSuspense<TData = Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError = ActionsActionGroupListActions400>(
 actionGroup: ActionGroupType, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActionsActionGroupListActionsSuspense<TData = Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError = ActionsActionGroupListActions400>(
 actionGroup: ActionGroupType, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListActions
 */

export function useActionsActionGroupListActionsSuspense<TData = Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError = ActionsActionGroupListActions400>(
 actionGroup: ActionGroupType, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupListActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getActionsActionGroupListActionsSuspenseQueryOptions(actionGroup,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary ExecuteAction
 */
export type actionsActionGroupExecuteActionResponse201 = {
  data: ActionExecutionResponse
  status: 201
}

export type actionsActionGroupExecuteActionResponse400 = {
  data: ActionsActionGroupExecuteAction400
  status: 400
}

export type actionsActionGroupExecuteActionResponseSuccess = (actionsActionGroupExecuteActionResponse201) & {
  headers: Headers;
};
export type actionsActionGroupExecuteActionResponseError = (actionsActionGroupExecuteActionResponse400) & {
  headers: Headers;
};

export type actionsActionGroupExecuteActionResponse = (actionsActionGroupExecuteActionResponseSuccess | actionsActionGroupExecuteActionResponseError)

export const getActionsActionGroupExecuteActionUrl = (actionGroup: ActionGroupType,) => {


  

  return `/actions/${actionGroup}`
}

export const actionsActionGroupExecuteAction = async (actionGroup: ActionGroupType,
    updateUserAction: UpdateUserAction, options?: RequestInit): Promise<actionsActionGroupExecuteActionResponse> => {
  
  return customInstance<actionsActionGroupExecuteActionResponse>(getActionsActionGroupExecuteActionUrl(actionGroup),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserAction,)
  }
);}
  



export const getActionsActionGroupExecuteActionMutationOptions = <TError = ActionsActionGroupExecuteAction400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof actionsActionGroupExecuteAction>>, TError,{actionGroup: ActionGroupType;data: UpdateUserAction}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof actionsActionGroupExecuteAction>>, TError,{actionGroup: ActionGroupType;data: UpdateUserAction}, TContext> => {

const mutationKey = ['actionsActionGroupExecuteAction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof actionsActionGroupExecuteAction>>, {actionGroup: ActionGroupType;data: UpdateUserAction}> = (props) => {
          const {actionGroup,data} = props ?? {};

          return  actionsActionGroupExecuteAction(actionGroup,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ActionsActionGroupExecuteActionMutationResult = NonNullable<Awaited<ReturnType<typeof actionsActionGroupExecuteAction>>>
    export type ActionsActionGroupExecuteActionMutationBody = UpdateUserAction
    export type ActionsActionGroupExecuteActionMutationError = ActionsActionGroupExecuteAction400

    /**
 * @summary ExecuteAction
 */
export const useActionsActionGroupExecuteAction = <TError = ActionsActionGroupExecuteAction400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof actionsActionGroupExecuteAction>>, TError,{actionGroup: ActionGroupType;data: UpdateUserAction}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof actionsActionGroupExecuteAction>>,
        TError,
        {actionGroup: ActionGroupType;data: UpdateUserAction},
        TContext
      > => {
      return useMutation(getActionsActionGroupExecuteActionMutationOptions(options), queryClient);
    }
    /**
 * @summary ListObjectActions
 */
export type actionsActionGroupObjectIdListObjectActionsResponse200 = {
  data: ActionListResponse
  status: 200
}

export type actionsActionGroupObjectIdListObjectActionsResponse400 = {
  data: ActionsActionGroupObjectIdListObjectActions400
  status: 400
}

export type actionsActionGroupObjectIdListObjectActionsResponseSuccess = (actionsActionGroupObjectIdListObjectActionsResponse200) & {
  headers: Headers;
};
export type actionsActionGroupObjectIdListObjectActionsResponseError = (actionsActionGroupObjectIdListObjectActionsResponse400) & {
  headers: Headers;
};

export type actionsActionGroupObjectIdListObjectActionsResponse = (actionsActionGroupObjectIdListObjectActionsResponseSuccess | actionsActionGroupObjectIdListObjectActionsResponseError)

export const getActionsActionGroupObjectIdListObjectActionsUrl = (actionGroup: ActionGroupType,
    objectId: number,) => {


  

  return `/actions/${actionGroup}/${objectId}`
}

export const actionsActionGroupObjectIdListObjectActions = async (actionGroup: ActionGroupType,
    objectId: number, options?: RequestInit): Promise<actionsActionGroupObjectIdListObjectActionsResponse> => {
  
  return customInstance<actionsActionGroupObjectIdListObjectActionsResponse>(getActionsActionGroupObjectIdListObjectActionsUrl(actionGroup,objectId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getActionsActionGroupObjectIdListObjectActionsQueryKey = (actionGroup: ActionGroupType,
    objectId: number,) => {
    return [
    `/actions/${actionGroup}/${objectId}`
    ] as const;
    }

    
export const getActionsActionGroupObjectIdListObjectActionsQueryOptions = <TData = Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError = ActionsActionGroupObjectIdListObjectActions400>(actionGroup: ActionGroupType,
    objectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getActionsActionGroupObjectIdListObjectActionsQueryKey(actionGroup,objectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>> = ({ signal }) => actionsActionGroupObjectIdListObjectActions(actionGroup,objectId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(actionGroup && objectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ActionsActionGroupObjectIdListObjectActionsQueryResult = NonNullable<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>>
export type ActionsActionGroupObjectIdListObjectActionsQueryError = ActionsActionGroupObjectIdListObjectActions400


export function useActionsActionGroupObjectIdListObjectActions<TData = Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError = ActionsActionGroupObjectIdListObjectActions400>(
 actionGroup: ActionGroupType,
    objectId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>,
          TError,
          Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActionsActionGroupObjectIdListObjectActions<TData = Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError = ActionsActionGroupObjectIdListObjectActions400>(
 actionGroup: ActionGroupType,
    objectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>,
          TError,
          Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActionsActionGroupObjectIdListObjectActions<TData = Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError = ActionsActionGroupObjectIdListObjectActions400>(
 actionGroup: ActionGroupType,
    objectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListObjectActions
 */

export function useActionsActionGroupObjectIdListObjectActions<TData = Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError = ActionsActionGroupObjectIdListObjectActions400>(
 actionGroup: ActionGroupType,
    objectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getActionsActionGroupObjectIdListObjectActionsQueryOptions(actionGroup,objectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getActionsActionGroupObjectIdListObjectActionsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError = ActionsActionGroupObjectIdListObjectActions400>(actionGroup: ActionGroupType,
    objectId: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getActionsActionGroupObjectIdListObjectActionsQueryKey(actionGroup,objectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>> = ({ signal }) => actionsActionGroupObjectIdListObjectActions(actionGroup,objectId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ActionsActionGroupObjectIdListObjectActionsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>>
export type ActionsActionGroupObjectIdListObjectActionsSuspenseQueryError = ActionsActionGroupObjectIdListObjectActions400


export function useActionsActionGroupObjectIdListObjectActionsSuspense<TData = Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError = ActionsActionGroupObjectIdListObjectActions400>(
 actionGroup: ActionGroupType,
    objectId: number, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActionsActionGroupObjectIdListObjectActionsSuspense<TData = Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError = ActionsActionGroupObjectIdListObjectActions400>(
 actionGroup: ActionGroupType,
    objectId: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActionsActionGroupObjectIdListObjectActionsSuspense<TData = Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError = ActionsActionGroupObjectIdListObjectActions400>(
 actionGroup: ActionGroupType,
    objectId: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListObjectActions
 */

export function useActionsActionGroupObjectIdListObjectActionsSuspense<TData = Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError = ActionsActionGroupObjectIdListObjectActions400>(
 actionGroup: ActionGroupType,
    objectId: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdListObjectActions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getActionsActionGroupObjectIdListObjectActionsSuspenseQueryOptions(actionGroup,objectId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary ExecuteObjectAction
 */
export type actionsActionGroupObjectIdExecuteObjectActionResponse201 = {
  data: ActionExecutionResponse
  status: 201
}

export type actionsActionGroupObjectIdExecuteObjectActionResponse400 = {
  data: ActionsActionGroupObjectIdExecuteObjectAction400
  status: 400
}

export type actionsActionGroupObjectIdExecuteObjectActionResponseSuccess = (actionsActionGroupObjectIdExecuteObjectActionResponse201) & {
  headers: Headers;
};
export type actionsActionGroupObjectIdExecuteObjectActionResponseError = (actionsActionGroupObjectIdExecuteObjectActionResponse400) & {
  headers: Headers;
};

export type actionsActionGroupObjectIdExecuteObjectActionResponse = (actionsActionGroupObjectIdExecuteObjectActionResponseSuccess | actionsActionGroupObjectIdExecuteObjectActionResponseError)

export const getActionsActionGroupObjectIdExecuteObjectActionUrl = (actionGroup: ActionGroupType,
    objectId: number,) => {


  

  return `/actions/${actionGroup}/${objectId}`
}

export const actionsActionGroupObjectIdExecuteObjectAction = async (actionGroup: ActionGroupType,
    objectId: number,
    updateUserAction: UpdateUserAction, options?: RequestInit): Promise<actionsActionGroupObjectIdExecuteObjectActionResponse> => {
  
  return customInstance<actionsActionGroupObjectIdExecuteObjectActionResponse>(getActionsActionGroupObjectIdExecuteObjectActionUrl(actionGroup,objectId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserAction,)
  }
);}
  



export const getActionsActionGroupObjectIdExecuteObjectActionMutationOptions = <TError = ActionsActionGroupObjectIdExecuteObjectAction400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdExecuteObjectAction>>, TError,{actionGroup: ActionGroupType;objectId: number;data: UpdateUserAction}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdExecuteObjectAction>>, TError,{actionGroup: ActionGroupType;objectId: number;data: UpdateUserAction}, TContext> => {

const mutationKey = ['actionsActionGroupObjectIdExecuteObjectAction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof actionsActionGroupObjectIdExecuteObjectAction>>, {actionGroup: ActionGroupType;objectId: number;data: UpdateUserAction}> = (props) => {
          const {actionGroup,objectId,data} = props ?? {};

          return  actionsActionGroupObjectIdExecuteObjectAction(actionGroup,objectId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ActionsActionGroupObjectIdExecuteObjectActionMutationResult = NonNullable<Awaited<ReturnType<typeof actionsActionGroupObjectIdExecuteObjectAction>>>
    export type ActionsActionGroupObjectIdExecuteObjectActionMutationBody = UpdateUserAction
    export type ActionsActionGroupObjectIdExecuteObjectActionMutationError = ActionsActionGroupObjectIdExecuteObjectAction400

    /**
 * @summary ExecuteObjectAction
 */
export const useActionsActionGroupObjectIdExecuteObjectAction = <TError = ActionsActionGroupObjectIdExecuteObjectAction400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof actionsActionGroupObjectIdExecuteObjectAction>>, TError,{actionGroup: ActionGroupType;objectId: number;data: UpdateUserAction}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof actionsActionGroupObjectIdExecuteObjectAction>>,
        TError,
        {actionGroup: ActionGroupType;objectId: number;data: UpdateUserAction},
        TContext
      > => {
      return useMutation(getActionsActionGroupObjectIdExecuteObjectActionMutationOptions(options), queryClient);
    }
    