/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Cuida API
 * Cuida backend API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  UserSchema,
  UsersUserIdGetUser400
} from '../cuidaAPI.schemas';

import { customInstance } from '.././custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary GetUser
 */
export type usersUserIdGetUserResponse200 = {
  data: UserSchema
  status: 200
}

export type usersUserIdGetUserResponse400 = {
  data: UsersUserIdGetUser400
  status: 400
}

export type usersUserIdGetUserResponseSuccess = (usersUserIdGetUserResponse200) & {
  headers: Headers;
};
export type usersUserIdGetUserResponseError = (usersUserIdGetUserResponse400) & {
  headers: Headers;
};

export type usersUserIdGetUserResponse = (usersUserIdGetUserResponseSuccess | usersUserIdGetUserResponseError)

export const getUsersUserIdGetUserUrl = (userId: number,) => {


  

  return `/users/${userId}`
}

export const usersUserIdGetUser = async (userId: number, options?: RequestInit): Promise<usersUserIdGetUserResponse> => {
  
  return customInstance<usersUserIdGetUserResponse>(getUsersUserIdGetUserUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getUsersUserIdGetUserQueryKey = (userId: number,) => {
    return [
    `/users/${userId}`
    ] as const;
    }

    
export const getUsersUserIdGetUserQueryOptions = <TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersUserIdGetUserQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersUserIdGetUser>>> = ({ signal }) => usersUserIdGetUser(userId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersUserIdGetUserQueryResult = NonNullable<Awaited<ReturnType<typeof usersUserIdGetUser>>>
export type UsersUserIdGetUserQueryError = UsersUserIdGetUser400


export function useUsersUserIdGetUser<TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(
 userId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUserIdGetUser>>,
          TError,
          Awaited<ReturnType<typeof usersUserIdGetUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUserIdGetUser<TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUserIdGetUser>>,
          TError,
          Awaited<ReturnType<typeof usersUserIdGetUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUserIdGetUser<TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetUser
 */

export function useUsersUserIdGetUser<TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersUserIdGetUserQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getUsersUserIdGetUserSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(userId: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersUserIdGetUserQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersUserIdGetUser>>> = ({ signal }) => usersUserIdGetUser(userId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersUserIdGetUserSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof usersUserIdGetUser>>>
export type UsersUserIdGetUserSuspenseQueryError = UsersUserIdGetUser400


export function useUsersUserIdGetUserSuspense<TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(
 userId: number, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUserIdGetUserSuspense<TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(
 userId: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUserIdGetUserSuspense<TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(
 userId: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetUser
 */

export function useUsersUserIdGetUserSuspense<TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(
 userId: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersUserIdGetUserSuspenseQueryOptions(userId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary ListUsers
 */
export type usersListUsersResponse200 = {
  data: UserSchema[]
  status: 200
}

export type usersListUsersResponseSuccess = (usersListUsersResponse200) & {
  headers: Headers;
};
;

export type usersListUsersResponse = (usersListUsersResponseSuccess)

export const getUsersListUsersUrl = () => {


  

  return `/users`
}

export const usersListUsers = async ( options?: RequestInit): Promise<usersListUsersResponse> => {
  
  return customInstance<usersListUsersResponse>(getUsersListUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getUsersListUsersQueryKey = () => {
    return [
    `/users`
    ] as const;
    }

    
export const getUsersListUsersQueryOptions = <TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersListUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersListUsers>>> = ({ signal }) => usersListUsers({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof usersListUsers>>>
export type UsersListUsersQueryError = unknown


export function useUsersListUsers<TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersListUsers>>,
          TError,
          Awaited<ReturnType<typeof usersListUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersListUsers<TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersListUsers>>,
          TError,
          Awaited<ReturnType<typeof usersListUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersListUsers<TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListUsers
 */

export function useUsersListUsers<TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersListUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getUsersListUsersSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersListUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersListUsers>>> = ({ signal }) => usersListUsers({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersListUsersSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof usersListUsers>>>
export type UsersListUsersSuspenseQueryError = unknown


export function useUsersListUsersSuspense<TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersListUsersSuspense<TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersListUsersSuspense<TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListUsers
 */

export function useUsersListUsersSuspense<TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersListUsersSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




