"""add tasks table

Revision ID: d2c4871884f1
Revises: a1b2c3d4e5f6
Create Date: 2026-03-15 01:07:18.154640+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2c4871884f1"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    emailmessagestatus = sa.Enum("PENDING", "SENT", "FAILED", name="emailmessagestatus")
    emailmessagestatus.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "email_messages",
        sa.Column("status", sa.Enum("PENDING", "SENT", "FAILED", name="emailmessagestatus"), nullable=False),
    )
    op.add_column("email_messages", sa.Column("error_message", sa.Text(), nullable=True))
    op.add_column("tasks", sa.Column("task_name", sa.Text(), nullable=False))
    op.add_column("tasks", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("tasks", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f("ix_tasks_organization_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_job_key"), table_name="tasks")
    op.create_index(op.f("ix_tasks_job_key"), "tasks", ["job_key"], unique=True)
    op.create_index(op.f("ix_tasks_task_name"), "tasks", ["task_name"], unique=False)
    op.drop_constraint(op.f("tasks_organization_id_fkey"), "tasks", type_="foreignkey")
    op.drop_column("tasks", "organization_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(
        op.f("tasks_organization_id_fkey"), "tasks", "organizations", ["organization_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_index(op.f("ix_tasks_task_name"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_job_key"), table_name="tasks")
    op.create_index(op.f("ix_tasks_job_key"), "tasks", ["job_key"], unique=False)
    op.create_index(op.f("ix_tasks_organization_id"), "tasks", ["organization_id"], unique=False)
    op.drop_column("tasks", "completed_at")
    op.drop_column("tasks", "started_at")
    op.drop_column("tasks", "task_name")
    op.drop_column("email_messages", "error_message")
    op.drop_column("email_messages", "status")
    # ### end Alembic commands ###
