"""adapt user model

Revision ID: 665756c5e34c
Revises: 444051d863b1
Create Date: 2026-03-13 02:22:36.063923+00:00

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "665756c5e34c"
down_revision: str | None = "444051d863b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
