"""initial-models

Revision ID: 444051d863b1
Revises: 67cdf42961a9
Create Date: 2026-03-12 23:02:17.321710+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "444051d863b1"
down_revision: str | None = "67cdf42961a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_deleted_at"), "organizations", ["deleted_at"], unique=False)
    op.create_table(
        "task_schedules",
        sa.Column("cron", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_schedules_deleted_at"), "task_schedules", ["deleted_at"], unique=False)
    op.create_table(
        "addresses",
        sa.Column("line1", sa.Text(), nullable=False),
        sa.Column("line2", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("postal_code", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), server_default="US", nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_addresses_deleted_at"), "addresses", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_addresses_organization_id"), "addresses", ["organization_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("queue", sa.Text(), nullable=False),
        sa.Column("job_key", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_deleted_at"), "tasks", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_tasks_job_key"), "tasks", ["job_key"], unique=False)
    op.create_index(op.f("ix_tasks_organization_id"), "tasks", ["organization_id"], unique=False)
    op.create_table(
        "patients",
        sa.Column("address_id", sa.Integer(), nullable=True),
        sa.Column("call_schedule_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["address_id"], ["addresses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["call_schedule_id"], ["task_schedules.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patients_address_id"), "patients", ["address_id"], unique=False)
    op.create_index(op.f("ix_patients_call_schedule_id"), "patients", ["call_schedule_id"], unique=False)
    op.create_index(op.f("ix_patients_deleted_at"), "patients", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_patients_organization_id"), "patients", ["organization_id"], unique=False)
    op.create_table(
        "calendar_events",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_calendar_events_deleted_at"), "calendar_events", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_calendar_events_organization_id"), "calendar_events", ["organization_id"], unique=False)
    op.create_index(op.f("ix_calendar_events_patient_id"), "calendar_events", ["patient_id"], unique=False)
    op.create_index(op.f("ix_calendar_events_user_id"), "calendar_events", ["user_id"], unique=False)
    op.create_table(
        "contacts",
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contacts_deleted_at"), "contacts", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_contacts_organization_id"), "contacts", ["organization_id"], unique=False)
    op.create_index(op.f("ix_contacts_patient_id"), "contacts", ["patient_id"], unique=False)
    op.create_index(op.f("ix_contacts_user_id"), "contacts", ["user_id"], unique=False)
    op.create_table(
        "phone_calls",
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("recording_url", sa.Text(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("provider_call_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_phone_calls_contact_id"), "phone_calls", ["contact_id"], unique=False)
    op.create_index(op.f("ix_phone_calls_deleted_at"), "phone_calls", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_phone_calls_organization_id"), "phone_calls", ["organization_id"], unique=False)
    op.create_table(
        "text_messages",
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("provider_message_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_text_messages_contact_id"), "text_messages", ["contact_id"], unique=False)
    op.create_index(op.f("ix_text_messages_deleted_at"), "text_messages", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_text_messages_organization_id"), "text_messages", ["organization_id"], unique=False)
    op.create_table(
        "llm_threads",
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("phone_call_id", sa.Integer(), nullable=True),
        sa.Column("text_message_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["phone_call_id"], ["phone_calls.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["text_message_id"], ["text_messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_threads_deleted_at"), "llm_threads", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_llm_threads_organization_id"), "llm_threads", ["organization_id"], unique=False)
    op.create_index(op.f("ix_llm_threads_patient_id"), "llm_threads", ["patient_id"], unique=False)
    op.create_index(op.f("ix_llm_threads_phone_call_id"), "llm_threads", ["phone_call_id"], unique=False)
    op.create_index(op.f("ix_llm_threads_text_message_id"), "llm_threads", ["text_message_id"], unique=False)
    op.create_index(op.f("ix_llm_threads_user_id"), "llm_threads", ["user_id"], unique=False)
    op.create_table(
        "llm_messages",
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["llm_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_messages_deleted_at"), "llm_messages", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_llm_messages_thread_id"), "llm_messages", ["thread_id"], unique=False)
    op.add_column("users", sa.Column("phone", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("address_id", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("report_schedule_id", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("organization_id", sa.Integer(), nullable=False))
    op.alter_column("users", "name", existing_type=sa.VARCHAR(length=255), type_=sa.Text(), existing_nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(length=255), type_=sa.Text(), existing_nullable=False)
    op.create_index(op.f("ix_users_address_id"), "users", ["address_id"], unique=False)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_index(op.f("ix_users_report_schedule_id"), "users", ["report_schedule_id"], unique=False)
    op.create_foreign_key(None, "users", "task_schedules", ["report_schedule_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "users", "organizations", ["organization_id"], ["id"], ondelete="RESTRICT")
    op.create_foreign_key(None, "users", "addresses", ["address_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_report_schedule_id"), table_name="users")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_address_id"), table_name="users")
    op.alter_column("users", "email", existing_type=sa.Text(), type_=sa.VARCHAR(length=255), existing_nullable=False)
    op.alter_column("users", "name", existing_type=sa.Text(), type_=sa.VARCHAR(length=255), existing_nullable=False)
    op.drop_column("users", "organization_id")
    op.drop_column("users", "report_schedule_id")
    op.drop_column("users", "address_id")
    op.drop_column("users", "phone")
    op.drop_index(op.f("ix_llm_messages_thread_id"), table_name="llm_messages")
    op.drop_index(op.f("ix_llm_messages_deleted_at"), table_name="llm_messages")
    op.drop_table("llm_messages")
    op.drop_index(op.f("ix_llm_threads_user_id"), table_name="llm_threads")
    op.drop_index(op.f("ix_llm_threads_text_message_id"), table_name="llm_threads")
    op.drop_index(op.f("ix_llm_threads_phone_call_id"), table_name="llm_threads")
    op.drop_index(op.f("ix_llm_threads_patient_id"), table_name="llm_threads")
    op.drop_index(op.f("ix_llm_threads_organization_id"), table_name="llm_threads")
    op.drop_index(op.f("ix_llm_threads_deleted_at"), table_name="llm_threads")
    op.drop_table("llm_threads")
    op.drop_index(op.f("ix_text_messages_organization_id"), table_name="text_messages")
    op.drop_index(op.f("ix_text_messages_deleted_at"), table_name="text_messages")
    op.drop_index(op.f("ix_text_messages_contact_id"), table_name="text_messages")
    op.drop_table("text_messages")
    op.drop_index(op.f("ix_phone_calls_organization_id"), table_name="phone_calls")
    op.drop_index(op.f("ix_phone_calls_deleted_at"), table_name="phone_calls")
    op.drop_index(op.f("ix_phone_calls_contact_id"), table_name="phone_calls")
    op.drop_table("phone_calls")
    op.drop_index(op.f("ix_contacts_user_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_patient_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_organization_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_deleted_at"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_calendar_events_user_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_patient_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_organization_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_deleted_at"), table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_index(op.f("ix_patients_organization_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_deleted_at"), table_name="patients")
    op.drop_index(op.f("ix_patients_call_schedule_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_address_id"), table_name="patients")
    op.drop_table("patients")
    op.drop_index(op.f("ix_tasks_organization_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_job_key"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_deleted_at"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_addresses_organization_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_deleted_at"), table_name="addresses")
    op.drop_table("addresses")
    op.drop_index(op.f("ix_task_schedules_deleted_at"), table_name="task_schedules")
    op.drop_table("task_schedules")
    op.drop_index(op.f("ix_organizations_deleted_at"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
