"""add_org_invitation_tokens

Revision ID: c08f9c548cfa
Revises: 665756c5e34c
Create Date: 2026-03-13 18:15:53.001772+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c08f9c548cfa"
down_revision: str | None = "665756c5e34c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_invitation_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("invited_email", sa.Text(), nullable=False),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["invited_by_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_org_invitation_pending",
        "org_invitation_tokens",
        ["organization_id", "invited_email"],
        unique=True,
        postgresql_where=sa.text("accepted_at IS NULL"),
    )
    op.create_index(op.f("ix_org_invitation_tokens_deleted_at"), "org_invitation_tokens", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_org_invitation_tokens_invited_by_user_id"),
        "org_invitation_tokens",
        ["invited_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_org_invitation_tokens_invited_email"), "org_invitation_tokens", ["invited_email"], unique=False
    )
    op.create_index(
        op.f("ix_org_invitation_tokens_organization_id"), "org_invitation_tokens", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_org_invitation_tokens_token_hash"), "org_invitation_tokens", ["token_hash"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_org_invitation_tokens_token_hash"), table_name="org_invitation_tokens")
    op.drop_index(op.f("ix_org_invitation_tokens_organization_id"), table_name="org_invitation_tokens")
    op.drop_index(op.f("ix_org_invitation_tokens_invited_email"), table_name="org_invitation_tokens")
    op.drop_index(op.f("ix_org_invitation_tokens_invited_by_user_id"), table_name="org_invitation_tokens")
    op.drop_index(op.f("ix_org_invitation_tokens_deleted_at"), table_name="org_invitation_tokens")
    op.drop_index(
        "ix_org_invitation_pending", table_name="org_invitation_tokens", postgresql_where=sa.text("accepted_at IS NULL")
    )
    op.drop_table("org_invitation_tokens")
    # ### end Alembic commands ###
