/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Cuida API
 * Cuida backend API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AuthLogoutLogout201,
  AuthMagicLinkRequestRequestMagicLink201,
  AuthMagicLinkRequestRequestMagicLink400,
  AuthMagicLinkVerifyVerifyMagicLink400,
  AuthMagicLinkVerifyVerifyMagicLinkParams,
  AuthMeMe200,
  MagicLinkRequestBody
} from '../cuidaAPI.schemas';

import { customInstance } from '.././custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary RequestMagicLink
 */
export type authMagicLinkRequestRequestMagicLinkResponse201 = {
  data: AuthMagicLinkRequestRequestMagicLink201
  status: 201
}

export type authMagicLinkRequestRequestMagicLinkResponse400 = {
  data: AuthMagicLinkRequestRequestMagicLink400
  status: 400
}

export type authMagicLinkRequestRequestMagicLinkResponseSuccess = (authMagicLinkRequestRequestMagicLinkResponse201) & {
  headers: Headers;
};
export type authMagicLinkRequestRequestMagicLinkResponseError = (authMagicLinkRequestRequestMagicLinkResponse400) & {
  headers: Headers;
};

export type authMagicLinkRequestRequestMagicLinkResponse = (authMagicLinkRequestRequestMagicLinkResponseSuccess | authMagicLinkRequestRequestMagicLinkResponseError)

export const getAuthMagicLinkRequestRequestMagicLinkUrl = () => {


  

  return `/auth/magic-link/request`
}

export const authMagicLinkRequestRequestMagicLink = async (magicLinkRequestBody: MagicLinkRequestBody, options?: RequestInit): Promise<authMagicLinkRequestRequestMagicLinkResponse> => {
  
  return customInstance<authMagicLinkRequestRequestMagicLinkResponse>(getAuthMagicLinkRequestRequestMagicLinkUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      magicLinkRequestBody,)
  }
);}
  



export const getAuthMagicLinkRequestRequestMagicLinkMutationOptions = <TError = AuthMagicLinkRequestRequestMagicLink400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authMagicLinkRequestRequestMagicLink>>, TError,{data: MagicLinkRequestBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authMagicLinkRequestRequestMagicLink>>, TError,{data: MagicLinkRequestBody}, TContext> => {

const mutationKey = ['authMagicLinkRequestRequestMagicLink'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authMagicLinkRequestRequestMagicLink>>, {data: MagicLinkRequestBody}> = (props) => {
          const {data} = props ?? {};

          return  authMagicLinkRequestRequestMagicLink(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthMagicLinkRequestRequestMagicLinkMutationResult = NonNullable<Awaited<ReturnType<typeof authMagicLinkRequestRequestMagicLink>>>
    export type AuthMagicLinkRequestRequestMagicLinkMutationBody = MagicLinkRequestBody
    export type AuthMagicLinkRequestRequestMagicLinkMutationError = AuthMagicLinkRequestRequestMagicLink400

    /**
 * @summary RequestMagicLink
 */
export const useAuthMagicLinkRequestRequestMagicLink = <TError = AuthMagicLinkRequestRequestMagicLink400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authMagicLinkRequestRequestMagicLink>>, TError,{data: MagicLinkRequestBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authMagicLinkRequestRequestMagicLink>>,
        TError,
        {data: MagicLinkRequestBody},
        TContext
      > => {
      return useMutation(getAuthMagicLinkRequestRequestMagicLinkMutationOptions(options), queryClient);
    }
    /**
 * @summary VerifyMagicLink
 */
export type authMagicLinkVerifyVerifyMagicLinkResponse200 = {
  data: void
  status: 200
}

export type authMagicLinkVerifyVerifyMagicLinkResponse400 = {
  data: AuthMagicLinkVerifyVerifyMagicLink400
  status: 400
}

export type authMagicLinkVerifyVerifyMagicLinkResponseSuccess = (authMagicLinkVerifyVerifyMagicLinkResponse200) & {
  headers: Headers;
};
export type authMagicLinkVerifyVerifyMagicLinkResponseError = (authMagicLinkVerifyVerifyMagicLinkResponse400) & {
  headers: Headers;
};

export type authMagicLinkVerifyVerifyMagicLinkResponse = (authMagicLinkVerifyVerifyMagicLinkResponseSuccess | authMagicLinkVerifyVerifyMagicLinkResponseError)

export const getAuthMagicLinkVerifyVerifyMagicLinkUrl = (params: AuthMagicLinkVerifyVerifyMagicLinkParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/magic-link/verify?${stringifiedParams}` : `/auth/magic-link/verify`
}

export const authMagicLinkVerifyVerifyMagicLink = async (params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: RequestInit): Promise<authMagicLinkVerifyVerifyMagicLinkResponse> => {
  
  return customInstance<authMagicLinkVerifyVerifyMagicLinkResponse>(getAuthMagicLinkVerifyVerifyMagicLinkUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getAuthMagicLinkVerifyVerifyMagicLinkQueryKey = (params?: AuthMagicLinkVerifyVerifyMagicLinkParams,) => {
    return [
    `/auth/magic-link/verify`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAuthMagicLinkVerifyVerifyMagicLinkQueryOptions = <TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMagicLinkVerifyVerifyMagicLinkQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>> = ({ signal }) => authMagicLinkVerifyVerifyMagicLink(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMagicLinkVerifyVerifyMagicLinkQueryResult = NonNullable<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>>
export type AuthMagicLinkVerifyVerifyMagicLinkQueryError = AuthMagicLinkVerifyVerifyMagicLink400


export function useAuthMagicLinkVerifyVerifyMagicLink<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>,
          TError,
          Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMagicLinkVerifyVerifyMagicLink<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>,
          TError,
          Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMagicLinkVerifyVerifyMagicLink<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary VerifyMagicLink
 */

export function useAuthMagicLinkVerifyVerifyMagicLink<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMagicLinkVerifyVerifyMagicLinkQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getAuthMagicLinkVerifyVerifyMagicLinkSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMagicLinkVerifyVerifyMagicLinkQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>> = ({ signal }) => authMagicLinkVerifyVerifyMagicLink(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMagicLinkVerifyVerifyMagicLinkSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>>
export type AuthMagicLinkVerifyVerifyMagicLinkSuspenseQueryError = AuthMagicLinkVerifyVerifyMagicLink400


export function useAuthMagicLinkVerifyVerifyMagicLinkSuspense<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMagicLinkVerifyVerifyMagicLinkSuspense<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMagicLinkVerifyVerifyMagicLinkSuspense<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary VerifyMagicLink
 */

export function useAuthMagicLinkVerifyVerifyMagicLinkSuspense<TData = Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError = AuthMagicLinkVerifyVerifyMagicLink400>(
 params: AuthMagicLinkVerifyVerifyMagicLinkParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMagicLinkVerifyVerifyMagicLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMagicLinkVerifyVerifyMagicLinkSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Logout
 */
export type authLogoutLogoutResponse201 = {
  data: AuthLogoutLogout201
  status: 201
}

export type authLogoutLogoutResponseSuccess = (authLogoutLogoutResponse201) & {
  headers: Headers;
};
;

export type authLogoutLogoutResponse = (authLogoutLogoutResponseSuccess)

export const getAuthLogoutLogoutUrl = () => {


  

  return `/auth/logout`
}

export const authLogoutLogout = async ( options?: RequestInit): Promise<authLogoutLogoutResponse> => {
  
  return customInstance<authLogoutLogoutResponse>(getAuthLogoutLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  



export const getAuthLogoutLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogoutLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authLogoutLogout>>, TError,void, TContext> => {

const mutationKey = ['authLogoutLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogoutLogout>>, void> = () => {
          

          return  authLogoutLogout(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLogoutLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authLogoutLogout>>>
    
    export type AuthLogoutLogoutMutationError = unknown

    /**
 * @summary Logout
 */
export const useAuthLogoutLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogoutLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLogoutLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthLogoutLogoutMutationOptions(options), queryClient);
    }
    /**
 * @summary Me
 */
export type authMeMeResponse200 = {
  data: AuthMeMe200
  status: 200
}

export type authMeMeResponseSuccess = (authMeMeResponse200) & {
  headers: Headers;
};
;

export type authMeMeResponse = (authMeMeResponseSuccess)

export const getAuthMeMeUrl = () => {


  

  return `/auth/me`
}

export const authMeMe = async ( options?: RequestInit): Promise<authMeMeResponse> => {
  
  return customInstance<authMeMeResponse>(getAuthMeMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getAuthMeMeQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }

    
export const getAuthMeMeQueryOptions = <TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMeMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMeMe>>> = ({ signal }) => authMeMe({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMeMeQueryResult = NonNullable<Awaited<ReturnType<typeof authMeMe>>>
export type AuthMeMeQueryError = unknown


export function useAuthMeMe<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMeMe>>,
          TError,
          Awaited<ReturnType<typeof authMeMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMeMe<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMeMe>>,
          TError,
          Awaited<ReturnType<typeof authMeMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMeMe<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Me
 */

export function useAuthMeMe<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMeMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getAuthMeMeSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMeMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMeMe>>> = ({ signal }) => authMeMe({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMeMeSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof authMeMe>>>
export type AuthMeMeSuspenseQueryError = unknown


export function useAuthMeMeSuspense<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMeMeSuspense<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthMeMeSuspense<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Me
 */

export function useAuthMeMeSuspense<TData = Awaited<ReturnType<typeof authMeMe>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof authMeMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMeMeSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




