/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Cuida API
 * Cuida backend API
 * OpenAPI spec version: 0.1.0
 */
export interface MagicLinkRequestBody {
  email: string;
}

export type HealthHealthCheck200 = {[key: string]: string};

export type AuthMagicLinkRequestRequestMagicLink201 = {[key: string]: string};

/**
 * @nullable
 */
export type AuthMagicLinkRequestRequestMagicLink400Extra = {[key: string]: unknown} | unknown[] | null;

/**
 * Validation Exception
 */
export type AuthMagicLinkRequestRequestMagicLink400 = {
  status_code: number;
  detail: string;
  /** @nullable */
  extra?: AuthMagicLinkRequestRequestMagicLink400Extra;
};

export type AuthMagicLinkVerifyVerifyMagicLinkParams = {
token: string;
};

/**
 * @nullable
 */
export type AuthMagicLinkVerifyVerifyMagicLink400Extra = {[key: string]: unknown} | unknown[] | null;

/**
 * Validation Exception
 */
export type AuthMagicLinkVerifyVerifyMagicLink400 = {
  status_code: number;
  detail: string;
  /** @nullable */
  extra?: AuthMagicLinkVerifyVerifyMagicLink400Extra;
};

export type AuthLogoutLogout201 = {[key: string]: string};

export type AuthMeMe200 = { [key: string]: unknown };

